Models/Worker.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcTest.Models
{
    public class Department
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Worker> Workers { get; set; }
    }

    public class Worker
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите имя!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите фамилию!")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите отчество!")]
        public string Patronymic { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите телефон!")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите отдел!")]
        public int DepartmentID { get; set; }
        public Department Department { get; set; }

        public string PathPhoto { get; set; }

        public string FullName { get; set; }

    }
}

Models/WorkerViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace MvcTest.Models
{
    public class WorkerViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите имя!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите фамилию!")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите отчество!")]
        public string Patronymic { get; set; }


        [Required(ErrorMessage = "Пожалуйста, введите телефон!")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите отдел!")]
        public int DepartmentID { get; set; }

        public Department Department { get; set; }

        public string PathPhoto { get; set; }

        public IFormFile Photo { get; set; }

    }
}

Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTest.Data;
using System.Linq;
using MvcTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Microsoft.AspNetCore.Hosting;
using MvcTest.Utils;
using System.Threading.Tasks;

namespace MvcTest.Controllers
{
    public class WorkerController : Controller
    {

        private readonly DataContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;


        public WorkerController(DataContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
        }


        //Вывод таблицы 
        [HttpGet]
        public async Task<IActionResult> Index(int currentPageIndex=1,  string searchBy = "", string searchValue = "")
        {

            return View(await GetWorkerList(currentPageIndex, searchBy, searchValue));
        }


        private async Task<PageInfo> GetWorkerList(int currentPage, string searchBy, string searchValue)
        {
            double pageCount;
            int maxRowsPerPage = 7;
            PageInfo pageModel = new PageInfo();   
            
            if (string.IsNullOrEmpty(searchValue))
            {
                pageModel.Workers = await _context.Workers.Include(w => w.Department)
                                                   .OrderByDescending(w => w.Id)
                                                   .Skip((currentPage - 1) * maxRowsPerPage)
                                                   .Take(maxRowsPerPage).ToListAsync();

                pageCount = (double)((decimal)_context.Workers.Count() / Convert.ToDecimal(maxRowsPerPage));
            }
            else
            {
                switch (searchBy)
                {
                    case "FullName":
                        pageModel.Workers = await _context.Workers.Include(w => w.Department)
                                                    .Where(w => w.FullName.Contains(searchValue))
                                                    .OrderByDescending(w => w.Id)
                                                    .Skip((currentPage - 1) * maxRowsPerPage)
                                                    .Take(maxRowsPerPage).ToListAsync();

                        pageCount = (double)((decimal)_context.Workers.Where(w => w.FullName.Contains(searchValue))
                                                                             .Count() / Convert.ToDecimal(maxRowsPerPage));
                        break;

                    case "Phone":
                        pageModel.Workers = await _context.Workers.Include(w => w.Department)
                                                    .Where(w => w.Phone.StartsWith(searchValue))
                                                    .OrderByDescending(w => w.Id)
                                                    .Skip((currentPage - 1) * maxRowsPerPage)
                                                    .Take(maxRowsPerPage).ToListAsync();

                        pageCount = (double)((decimal)_context.Workers.Where(w => w.Phone.StartsWith(searchValue))
                                                                             .Count() / Convert.ToDecimal(maxRowsPerPage));

                        break;

                    default:
                        {
                            pageModel.Workers = await _context.Workers.Include(w => w.Department)
                                                   .OrderByDescending(w => w.Id)
                                                   .Skip((currentPage - 1) * maxRowsPerPage)
                                                   .Take(maxRowsPerPage).ToListAsync();

                            pageCount = (double)((decimal)_context.Workers.Where(w => w.FullName.Contains(searchValue))
                                                                             .Count() / Convert.ToDecimal(maxRowsPerPage));

                            break;
                        }
                }
            }
            
            pageModel.PageCount = (int)Math.Ceiling(pageCount);
            pageModel.CurrentPageIndex = currentPage;
            return pageModel;
        
        }

        //Создание сотрудника
        [HttpGet]
        public IActionResult Create()
        {
            SelectList departments = new SelectList(_context.Department, "Id", "Title");
            ViewBag.Departments = departments;
            return View();
        }

        [HttpPost]
        public IActionResult Create(WorkerViewModel model)
        {
            WorkerUtils utils = new WorkerUtils(webHostEnvironment);
            try
            {
                if (ModelState.IsValid)
                {
                    string uniqueFileName = utils.UploadedFile(model);
                    Worker worker = new Worker 
                    { 
                        Name = model.Name,
                        Surname = model.Surname,
                        Patronymic = model.Patronymic,
                        FullName = $"{model.Surname} {model.Name} {model.Patronymic}",
                        Phone = model.Phone,
                        DepartmentID = model.DepartmentID,
                        PathPhoto = uniqueFileName
                    };
                    _context.Workers.Add(worker);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Сотрудник добавален.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Данные сотрудника введены некорректно.";
                    return Create();
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return Create();
            }
        }

        //Обновление информации о сотруднике
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                Worker model = _context.Workers.SingleOrDefault(w => w.Id == id);
                var worker = new WorkerViewModel
                {
                    Name = model.Name,
                    Surname = model.Surname,
                    Patronymic = model.Patronymic,
                    Phone = model.Phone,
                    DepartmentID = model.DepartmentID,
                    PathPhoto = model.PathPhoto
                };

                if (worker != null)
                {
                    SelectList departments = new SelectList(_context.Department, "Id", "Title");
                    ViewBag.Departments = departments;
                    return View(worker);
                }
                else
                {
                    TempData["ErrorMessage"] = "Сотрудник с данным ID не найден.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Edit(WorkerViewModel model)
        {
            WorkerUtils utils = new WorkerUtils(webHostEnvironment);
            try
            {
                if (ModelState.IsValid)
                {
                    string pathPhoto = null;
                    if (model.Photo != null && utils.CheckExt(model.Photo.FileName))
                    {   
                        System.IO.File.Delete(utils.GetPathPhoto(model.PathPhoto));
                        pathPhoto = utils.UploadedFile(model);
                    }
                    else
                    {
                        pathPhoto = model.PathPhoto;
                    }


                    Worker worker = new Worker
                    {   
                        Id = model.Id,
                        Name = model.Name,
                        Surname = model.Surname,
                        Patronymic = model.Patronymic,
                        FullName = $"{model.Surname} {model.Name} {model.Patronymic}",
                        Phone = model.Phone,
                        DepartmentID = model.DepartmentID,
                        PathPhoto = pathPhoto
                    };

                    _context.Workers.Update(worker);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Информация о сотруднике обновлена.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Данные сотрудника введены некорректно.";
                    return Edit(model.Id);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return Edit(model.Id);
            }
        }


        //Удаление информации о сотруднике
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            try
            {
                Worker worker = _context.Workers.Include(w => w.Department).SingleOrDefault(w => w.Id == id);

                if (worker != null)
                {
                    return View(worker);
                }
                else
                {
                    TempData["ErrorMessage"] = "Сотрудник с данным ID не найден.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Delete(Worker model)
        {
            WorkerUtils utils = new WorkerUtils(webHostEnvironment);
            try
            {

Views/Worker/Create.cshtml
@model MvcTest.Models.WorkerViewModel

@{
    ViewData["Title"] = "Добавить сотрудника";
    var errorMessage = TempData["errorMessage"]?.ToString();
}


<div class="title row">
    <div class="col-8">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-4">
        <a asp-action="Index" type="button" class="close" aria-label="Close" style="font-size: 3rem;">
        <span aria-hidden="true">&times;</span>
        </a>
    </div>
</div>
<hr />

@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <strong>Ошибка! </strong>@errorMessage
    </div>
}

<form action="Create" method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label class="form-label">Имя</label>
        <input type="text" class="form-control" asp-for="Name"/>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Name)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Фамилия</label>
        <input type="text" class="form-control" asp-for="Surname" />
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Surname)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Отчество</label>
        <input type="text" class="form-control" asp-for="Patronymic" />
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Patronymic)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Телефон</label>
        <input type="text" class="form-control" asp-for="Phone" id="phone"/>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Phone)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Отдел</label>
        <br/>
        <select class="form-control form-control-l" asp-for="DepartmentID" asp-items="ViewBag.Departments" asp-values>
        </select>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.DepartmentID)</span>
    </div>

    <div class="mb-3">
        <label>Выберите фото (.jpg, .jpeg, .png)</label>
        <input class="form-control" type="file" asp-for="Photo" required>
    </div>                     
          

    <div class="d-grid">
        <button type="submit" class="bnt btn-success btn-lg btn-block">Добавить</button>
    </div>
</form>

Views/Worker/Delete.cshtml
@model MvcTest.Models.Worker

@{
    ViewData["Title"] = "Вы действительно хотите удалить данного сотрудника?";
}

<div class="title row">
    <div class="col-8">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-4">
        <a asp-action="Index" type="button" class="close" aria-label="Close" style="font-size: 3rem;">
            <span aria-hidden="true">&times;</span>
        </a>
    </div>
</div>
<hr />

<form action="Delete" method="post">
    @Html.HiddenFor(model => model.Id)

    <div class="text-center">
    <img src ="~/images/@Model.PathPhoto"      
             height="180"  width="180"
             asp-append-version="true" />
    </div>

    <div class="mb-3">
        <label class="form-label">Имя</label>
        <input type="text" class="form-control" asp-for="Name" readonly/>
    </div>

    <div class="mb-3">
        <label class="form-label">Фамилия</label>
        <input type="text" class="form-control" asp-for="Surname" readonly />
    </div>

    <div class="mb-3">
        <label class="form-label">Отчество</label>
        <input type="text" class="form-control" asp-for="Patronymic" readonly />
    </div>

    <div class="mb-3">
        <label class="form-label">Телефон</label>
        <input type="text" class="form-control" asp-for="Phone"  readonly/>
    </div>

    <div class="mb-3">
        <label class="form-label">Отдел</label>
        <input type="text" class="form-control" asp-for="Department.Title" readonly />
    </div>

    <div class="d-grid">
        <button type="submit" class="bnt btn-danger btn-lg btn-block">Удалить</button>
    </div>
</form>

Views/Worker/Edit.cshtml
@model MvcTest.Models.WorkerViewModel

@{
    ViewData["Title"] = "Изменить информацию о сотруднике";
    var errorMessage = TempData["errorMessage"]?.ToString();
}

<div class="title row">
    <div class="col-8">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-4">
        <a asp-action="Index" type="button" class="close" aria-label="Close" style="font-size: 3rem;">
            <span aria-hidden="true">&times;</span>
        </a>
    </div>
</div>
<hr />

@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <strong>Ошибка! </strong>@errorMessage
    </div>
}

<form action="Edit" method="post" enctype="multipart/form-data">

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.PathPhoto)

    <div class="mb-3">
        <label class="form-label">Имя</label>
        <input type="text" class="form-control" asp-for="Name" />
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Name)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Фамилия</label>
        <input type="text" class="form-control" asp-for="Surname" />
         <span class="text-danger">@Html.ValidationMessageFor(model => model.Surname)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Отчество</label>
        <input type="text" class="form-control" asp-for="Patronymic" />
         <span class="text-danger">@Html.ValidationMessageFor(model => model.Patronymic)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Телефон</label>
        <input type="text" class="form-control" asp-for="Phone" id="phone"/>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Phone)</span>
    </div>

    <div class="mb-3">
        <label class="form-label">Отдел</label>
        <select class="form-control form-control-l" asp-for="DepartmentID" asp-items="ViewBag.Departments">
        </select>
        <span class="text-danger">@Html.ValidationMessageFor(model => model.DepartmentID)</span>
    </div>

    <div class="mb-3">
        <label>Заменить фото (.jpg, .jpeg, .png)</label>
        <input class="form-control" type="file" asp-for="Photo">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Photo)</span>
    </div>

    <div class="d-grid">
        <button type="submit" class="bnt btn-success btn-lg btn-block">Изменить</button>
    </div>
</form>

Views/Worker/Index.cshtml
@model MvcTest.Models.PageInfo



@{
    ViewData["Title"] = "Справочник сотрудников";
    var successMessage = TempData["successMessage"]?.ToString();
    var errorMessage = TempData["errorMessage"]?.ToString();
}




<form asp-action="Index" asp-controller="Worker" method="get">

    <div class="title row">
        <div class="col-4">
            <h3>@ViewData["Title"]</h3>
        </div>

        <div class="row col-6">
            <div class="col-2">
                <select class="form-select" name="searchBy" id="SearchBy" style="height: 80%">
                    <option value="FullName">ФИО</option>
                    <option value="Phone">Телефон</option>
                </select>
            </div>
            <div class="col-10">
                <input type="text" class="form-control" name="searchValue" placeholder="поиск" id="SearchValue" style="margin-left: 5%" />
            </div>

        </div>

        <div class="col-2">
            <a asp-controller='Worker' asp-action="Create" class="btn btn-success btn-lg float-right">
                Добавить
            </a>
        </div>
    </div>

    @if (!string.IsNullOrWhiteSpace(successMessage))
    {
        <div class="alert alert-success">
            <strong>Успешно! </strong>@successMessage
        </div>
    }
    else if (!string.IsNullOrWhiteSpace(errorMessage))
    {
        <div class="alert alert-danger">
            <strong>Ошибка! </strong>@errorMessage
        </div>
    }



    <table class="table">

        <thead style="border-top: none">
            <tr>
                <th style="width: 10%" scope="col">Фото</th>
                <th style="width: 30%" scope="col">ФИО</th>
                <th style="width: 20%" scope="col">Телефон</th>
                <th style="width: 20%" scope="col">Отдел</th>
                <th style="width: 20%" class="action"></th>
            </tr>
        </thead>

        <tbody id="Data">
            @if (Model != null && Model.Workers.Any())
            {
                @foreach (var worker in Model.Workers)
                {
                    <tr>
                        <td>
                            <img src ="~/images/@worker.PathPhoto"    
                                                      class="rounded-circle"    
                                                      height="60"  width="60"    
                                                      asp-append-version="true"   />
                        </td>
                        <td>@worker.FullName</td>
                        <td>@worker.Phone</td>
                        <td>@worker.Department.Title</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller='Worker' asp-action="Edit" asp-route-id="@worker.Id" class="btn btn-primary">
                                    Изменить
                                </a>
                                <a asp-controller='Worker' asp-action="Delete" asp-route-id="@worker.Id" class="btn btn-danger">
                                    Удалить
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">
                        <div class="align-content-center">
                            <h2> Сотрудники не найдены. </h2>
                        </div>
                    </td>
                </tr>
            }

                <ul class ="pagination" id="Pagination">
                    @for (int i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="page-item">

                            @if (i != Model.CurrentPageIndex)
                            {
                            <a class="page-link" href="#">@i</a>
                            }
                            else
                            {
                                <a class="page-link">@i</a>
                            }
                        </li>
                    }
                </ul>
        </tbody>
    </table>
</form>